function varargout=sys_hill(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=2;
   return
  case 'argrange'
   varargout{1}=struct('x',1:2,'p',3:6);
   return
  case 'argsize'
   varargout{1}=struct('x',2,'p',4);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=3;
   return
end
nout=2;
order=varargin{1};
f=str2func(sprintf('sys_hill_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2] = sys_hill_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%SYS_HILL_RHS_0
%    [OUT1,OUT2] = SYS_HILL_RHS_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    31-Oct-2024 15:57:26

t2 = in5+in6;
t3 = in5.^2;
t4 = in6.^2;
t5 = -in3;
t6 = -t4;
t7 = 1.0./t2.^2;
t8 = in4+t3+t6;
t9 = in4.*t7.*t8;
t10 = -t9;
out1 = -in4+t5+t10+in2.*in5.*2.0+in1.^2;
if nargout > 1
    out2 = in4+t5+t10+in1.*in6.*2.0+in2.^2;
end
end


function [out1,out2] = sys_hill_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%SYS_HILL_RHS_1
%    [OUT1,OUT2] = SYS_HILL_RHS_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    31-Oct-2024 15:57:26

t2 = in5+in6;
t3 = in11+in12;
t4 = in5.^2;
t5 = in6.^2;
t6 = in5.*in11.*2.0;
t7 = in6.*in12.*2.0;
t8 = -in9;
t9 = -t7;
t10 = -t5;
t11 = 1.0./t2.^2;
t12 = 1.0./t2.^3;
t13 = in10+t6+t9;
t14 = in4+t4+t10;
t15 = in10.*t11.*t14;
t16 = in4.*t11.*t13;
t19 = in4.*t3.*t12.*t14.*2.0;
t17 = -t15;
t18 = -t16;
out1 = -in10+t8+t17+t18+t19+in1.*in7.*2.0+in2.*in11.*2.0+in5.*in8.*2.0;
if nargout > 1
    out2 = in10+t8+t17+t18+t19+in2.*in8.*2.0+in1.*in12.*2.0+in6.*in7.*2.0;
end
end


function [out1,out2] = sys_hill_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%SYS_HILL_RHS_2
%    [OUT1,OUT2] = SYS_HILL_RHS_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    31-Oct-2024 15:57:26

t2 = in5+in6;
t3 = in11+in12;
t4 = in5.^2;
t5 = in6.^2;
t6 = in11.^2;
t7 = in12.^2;
t8 = in5.*in11.*2.0;
t9 = in6.*in12.*2.0;
t10 = t6.*2.0;
t11 = t7.*2.0;
t12 = -t9;
t13 = t3.^2;
t14 = -t5;
t16 = 1.0./t2.^2;
t17 = 1.0./t2.^3;
t15 = -t11;
t18 = t16.^2;
t19 = in10+t8+t12;
t20 = in4+t4+t14;
t21 = t10+t15;
t23 = in10.*t16.*t19.*2.0;
t26 = in10.*t3.*t17.*t20.*4.0;
t27 = in4.*t3.*t17.*t19.*4.0;
t28 = in4.*t13.*t18.*t20.*6.0;
t22 = in4.*t16.*t21;
t24 = -t23;
t29 = -t28;
t25 = -t22;
out1 = t24+t25+t26+t27+t29+in8.*in11.*4.0+in7.^2.*2.0;
if nargout > 1
    out2 = t24+t25+t26+t27+t29+in7.*in12.*4.0+in8.^2.*2.0;
end
end


function [out1,out2] = sys_hill_rhs_3(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12)
%SYS_HILL_RHS_3
%    [OUT1,OUT2] = SYS_HILL_RHS_3(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    31-Oct-2024 15:57:26

t2 = in5+in6;
t3 = in11+in12;
t4 = in5.^2;
t5 = in6.^2;
t6 = in11.^2;
t7 = in12.^2;
t8 = in5.*in11.*2.0;
t9 = in6.*in12.*2.0;
t10 = t6.*2.0;
t11 = t7.*2.0;
t12 = -t9;
t13 = t3.^2;
t14 = t3.^3;
t15 = -t5;
t17 = 1.0./t2.^2;
t18 = 1.0./t2.^3;
t20 = 1.0./t2.^5;
t16 = -t11;
t19 = t17.^2;
t21 = in10+t8+t12;
t22 = in4+t4+t15;
t23 = t10+t16;
t27 = in10.*t3.*t18.*t21.*1.2e+1;
t28 = in4.*t13.*t19.*t21.*1.8e+1;
t29 = in10.*t13.*t19.*t22.*1.8e+1;
t30 = in4.*t14.*t20.*t22.*2.4e+1;
t24 = in10.*t17.*t23.*3.0;
t26 = in4.*t3.*t18.*t23.*6.0;
t31 = -t28;
t32 = -t29;
t25 = -t24;
t33 = t25+t26+t27+t30+t31+t32;
out1 = t33;
if nargout > 1
    out2 = t33;
end
end

